version: "2"

linters:
  default: none
  enable:
    - bodyclose
    - copyloopvar
    - durationcheck
    - errcheck
    - errorlint
    - fatcontext
    - govet
    - ineffassign
    - modernize
    - nilerr
    - noctx
    - nolintlint
    - predeclared
    - staticcheck
    - unconvert
    - unused
    - usetesting
  settings:
    errcheck:
      check-type-assertions: true
    nolintlint:
      require-explanation: true
      require-specific: true
    usetesting:
      context-background: true
      context-todo: true
